import MainLayout from "../../components/main_layout/MainLayout";
// import "./globals.css";
// import { Inter } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Dinner-Pro",
//   description: "Generated by create next app",
//   icons: '/images/brand_logo/logo1.png'
// };

export default function RootLayout({ children }) {
  return (
        <main className="h-full w-full">
            <MainLayout>{children}</MainLayout>
        </main>
  );
}
