import Sidebar from "./components/navbar/sidebar";
import Topbar from "./components/navbar/topbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <main className="flex">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
