export const procurementTable = [
  {
    id: 1,
    itemName: "pepsi",
    category: "drinks",
    brand: "pepsiCo",
    quantity: 4,
    email: "test@example.com",
    status: "delivered",
  },
  {
    id: 2,
    itemName: "coke",
    category: "drinks",
    brand: "cocacola",
    quantity: 4,
    email: "test@example.com",
    status: "pending",
  },
  {
    id: 3,
    itemName: "pepsi",
    category: "drinks",
    brand: "pepsiCo",
    quantity: 4,
    email: "test@example.com",
    status: "pending",
  },
  {
    id: 4,
    itemName: "bigi",
    category: "drinks",
    brand: "bigi",
    quantity: 4,
    email: "test@example.com",
    status: "delivered",
  },
  {
    id: 5,
    itemName: "fanta",
    category: "drinks",
    brand: "cocacola",
    quantity: 4,
    email: "test@example.com",
    status: "pending",
  },
];
